apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-helm-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zkan/gitops-argocd-demo-deployment.git
    targetRevision: HEAD
    path: myapp-helm
    helm:
      releaseName: myapp-helm
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-helm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
